Changes for running and testing the roman_rubin catalog
LSSTDESC/descqa pull request #239
Opened 2023-11-28 18:23 UTC by evevkovacs

Here are the changes to get the Delta_Sigma and NumberDensityVersusRedshift tests to run with the latest versions of numpy, sklearn etc. These are minor code changes to the actual tests.
There is also an addition required to the run_master script to set the number of OMP_NUM_THREADS.  The issue is that the NumberDensityVersusRedshift test fails with an OPEN_BLAS error that complains about too many threads being used. (This is for a call to the kNN module in sklearn. ) The error did not occur when running on cori.  I have experimented with trying to set the number of OPEN_BLAS_THREADS and OMP_NUM_THREADS by calling  the python function to set these environmentals in the init function of NumberDensityVersusRedshift.py. None of these worked.  The only attempt that worked was to set the environmental from the master script.  I am of course open to better solutions.
Finally, there is a new configuration file for running the readiness test on the roman_rubin catalog.

2023-11-28 18:24 UTC, evevkovacs commented
@yymao Please review and comment. Thanks

2023-11-28 18:27 UTC, evevkovacs commented
Oops forgot to add:  the successful [NumberDensityVersusRedshift Test](https://portal.nersc.gov/cfs/lsst/descqa/v2/?run=2023-11-23&test=Nz_r_DEEP2_JAN) and the successful [Delta_Sigma Test](https://portal.nersc.gov/cfs/lsst/descqa/v2/?run=2023-11-17_13&test=delta_sigma_sdss_mainl)

2023-11-28 18:43 UTC, yymao requested changes
Thanks, @evevkovacs. I have two minor suggestions but otherwise it looks good to me.

2023-11-28 18:43 UTC, yymao commented on descqa/NumberDensityVersusRedshift.py
> +
```suggestion

```
Remove extra spaces

2023-11-28 18:43 UTC, yymao commented on descqa/DeltaSigmaTest.py
> +
```suggestion
            if not catalog_instance.has_quantities(['stellar_mass']):
                catalog_instance.add_derived_quantity('stellar_mass', np.add, 'stellar_mass_bulge', 'stellar_mass_disk')
            res = catalog_instance.get_quantities([
                 'redshift_true', 'ra', 'dec', 'shear_1', 'shear_2', 'stellar_mass',
                 'mag_true_i_sdss', 'mag_true_z_sdss','mag_true_g_sdss', 'mag_true_r_sdss',
                 'Mag_true_g_sdss_z0', 'Mag_true_r_sdss_z0',
             ])
            sm = res['stellar_mass']
```

Use `add_derived_quantity` when `stellar_mass` is not available to simply the logic here.

2023-11-28 18:53 UTC, evevkovacs commented
@yymao Thanks, I accepted both of your suggestions.

2023-11-28 18:57 UTC, yymao approved these changes

2023-11-28 18:58 UTC, merged

2023-11-28 20:25 UTC, evevkovacs commented
Running now on an interactive node...no failures yet.

2023-11-29 00:42 UTC, evevkovacs commented
OK, it ran... [see here](https://portal.nersc.gov/cfs/lsst/descqa/v2/?run=2023-11-28_1)